### ISSUE TITLE
File does not exist: config.json

### ISSUE THREAD

**Issue by iinviisiible** [ReversecLabs/physmem2profit#2]
Unfortunately, I haven't used rekall before, so I couldn't solve the below issue
The "dump" function has a config.json file which seems to be necessary to dump the remote physical memory. 

```
    CONFIG_FILE = 'config.json'
    print("[*] Loading config from %s" % (CONFIG_FILE))
    ensureFileExist(CONFIG_FILE)
    with open(CONFIG_FILE) as f:
        config = json.load(f)
```
and because it doesn't exist, "ensureFileExist()" crashes.

============= output on the client ============
[*] Connecting to 192.168.43.209 on port 8080
[*] Connected
[*] Loading config from config.json
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "__main__.py", line 57, in <lambda>
    jobs.append(Process(target=lambda: mount.mount(socket, args.driver, args.install)))     # mount will block thread, it need to be handled by child process.
  File "/root/Desktop/test/physmem2profit/client/mount.py", line 351, in mount
    fuse = FUSE(Physmem(sock, mountpoint, driver, installArguments), mountpoint, nothreads=True, foreground=True)
  File "/root/Desktop/test/physmem2profit/client/mount.py", line 46, in __init__
    raise Exception(struct.unpack("<%ds" % response, self.socket.recv(response))[0].decode('utf-8'))
Exception: Driver file does not exist.
[*] Read 0 MB, cached reads 0 MB
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "__main__.py", line 59, in <lambda>
    jobs.append(Process(target=lambda: physmem2minidump.dump(args.label)))
  File "/root/Desktop/test/physmem2profit/client/physmem2minidump.py", line 144, in dump
    ensureFileExist(CONFIG_FILE)
  File "/root/Desktop/test/physmem2profit/client/physmem2minidump.py", line 134, in ensureFileExist
    raise Exception('File does not exist: ' + path)
Exception: File does not exist: config.json

============================================

============ output on server =====================

[*] Registering driver bridges.
[+] Found driver bridge: WinPmem.
[+]    Registered command: Install.
[+]    Registered command: Uninstall.
[+]    Registered command: Map.
[+]    Registered command: Read.
[*] Starting server on 192.168.43.209:8080...
[+] Server Started.
[*] Waiting for a connection...
[+] Connected!
[*] Installing service...
[*] Creating service physmem2profit...
[-] Driver file does not exist.
=============================

Also, I don't know why the server can't find the driver (it does exist in the same directory).

**Comment by timhir** [comment]
The root cause here is that the driver is not loaded and the client cannot get the data needed for writing the config.json file. Most likely the issue is missing quotes for `—driver` argument. It should look something like this: `—driver ”c:\temp\att_winpmem_64.sys”`. The filepath needs to be the path to the driver on the _target_ system. I hope this solves the issue :).

We will update the README and slightly change the logic on the client side to better handle this error condition.
